name: Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release/**
jobs:
  build:
    permissions:
      checks: write
      statuses: write
      contents: write
      issues: write
      packages: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lego'
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Install Dependencies
        run: |
          pnpm install
      - name: Run build
        run: |
          pnpm build
      - name: Maybe release
        # if: !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
          PROTECTED_BRANCH_REVIEWER_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        run: |
          pnpm release:ci
